using System.Windows; using System.Windows.Controls; using Microsoft.Win32; using TVFongMi.Windows.Models; using TVFongMi.Windows.Services;
namespace TVFongMi.Windows;
public partial class MainWindow : Window
{
 private readonly SourceCatalog _catalog=new(); private readonly SourceImporter _importer=new(); private readonly SourceHealthChecker _healthChecker=new(); private readonly BackupService _backup=new(); private readonly CatVodHttpClient _api=new(); private readonly AppLogger _logger=new(); private readonly PlaybackService _playback; private IReadOnlyList<VideoItem> _allVideos=Array.Empty<VideoItem>(); private string _category="";
 public MainWindow(){InitializeComponent();_playback=new PlaybackService(new MpvPlayerBackend(PlayerLocator.FindMpv() ?? "mpv.exe"));RefreshSources();}
 private void RefreshSources(){SourceList.ItemsSource=null;SourceList.ItemsSource=_catalog.Sources;StatusText.Text=_catalog.Sources.Count==0?"尚未导入影视源":$"已加载 {_catalog.Sources.Count} 个影视源";}
 private async void CheckSources_Click(object sender,RoutedEventArgs e){if(_catalog.Sources.Count==0){MessageBox.Show("请先导入影视源。","提示");return;}try{var r=await _healthChecker.CheckAllAsync(_catalog.Sources);MessageBox.Show($"可访问 {r.Count(x=>x.IsReachable)}/{r.Count} 个影视源。","检查完成");}catch(Exception ex){MessageBox.Show(ex.Message,"检查失败");}}
 private async void Backup_Click(object sender,RoutedEventArgs e){var d=new SaveFileDialog{Filter="TVFongMi 备份|*.json",FileName="tvfongmi-backup.json"};if(d.ShowDialog()!=true)return;try{await _backup.ExportAsync(d.FileName);MessageBox.Show("配置备份完成。","完成");}catch(Exception ex){MessageBox.Show(ex.Message,"备份失败");}}
 private async void Restore_Click(object sender,RoutedEventArgs e){var d=new OpenFileDialog{Filter="TVFongMi 备份|*.json"};if(d.ShowDialog()!=true)return;try{await _backup.ImportAsync(d.FileName);RefreshSources();MessageBox.Show("配置恢复完成，部分设置将在重启后生效。","完成");}catch(Exception ex){MessageBox.Show(ex.Message,"恢复失败");}}
 private async void ImportUrl_Click(object sender,RoutedEventArgs e){var d=new UrlDialog();if(d.ShowDialog()!=true)return;try{var r=_catalog.Merge(await _importer.ImportFromUrlAsync(d.Url));RefreshSources();MessageBox.Show($"导入 {r.ImportedCount} 个影视源。","导入完成");}catch(Exception ex){MessageBox.Show(ex.Message,"导入失败");}}
 private async void ImportFile_Click(object sender,RoutedEventArgs e){var d=new OpenFileDialog{Filter="JSON 文件|*.json|所有文件|*.*"};if(d.ShowDialog()!=true)return;try{var r=_catalog.Merge(await _importer.ImportFromFileAsync(d.FileName));RefreshSources();MessageBox.Show($"导入 {r.ImportedCount} 个影视源。","导入完成");}catch(Exception ex){MessageBox.Show(ex.Message,"导入失败");}}
 private async void SourceList_SelectionChanged(object sender, SelectionChangedEventArgs e){if(SourceList.SelectedItem is not SourceConfig source)return;try{StatusText.Text=$"正在加载：{source.Name}";using var json=await _api.GetJsonAsync(source.Url);_allVideos=CatVodHttpClient.ReadVideoItems(json.RootElement);ApplySearch();StatusText.Text=$"{source.Name}：已加载 {_allVideos.Count} 个视频";}catch(Exception ex){_logger.Error($"加载影视源失败：{source.Name} ({source.Url})",ex);_allVideos=Array.Empty<VideoItem>();VideoList.ItemsSource=null;StatusText.Text=$"加载失败：{ex.Message}";}}
 private void SearchBox_TextChanged(object sender, TextChangedEventArgs e)=>ApplySearch();
 private void Category_SelectionChanged(object sender, SelectionChangedEventArgs e){if(sender is ListBox list && list.SelectedItem is ListBoxItem item)_category=item.Tag as string ?? "";ApplySearch();}
 private void ApplySearch(){var keyword=SearchBox?.Text?.Trim();IEnumerable<VideoItem> items=_allVideos;if(!string.IsNullOrWhiteSpace(_category))items=items.Where(x=>(x.Category??"").Contains(_category,StringComparison.OrdinalIgnoreCase));if(!string.IsNullOrWhiteSpace(keyword))items=items.Where(x=>x.Name.Contains(keyword,StringComparison.OrdinalIgnoreCase)||(x.Remark??"").Contains(keyword,StringComparison.OrdinalIgnoreCase));VideoList.ItemsSource=items.ToList();}
 private async void VideoCard_Click(object sender, System.Windows.Input.MouseButtonEventArgs e){if(sender is not FrameworkElement { DataContext: VideoItem video } || SourceList.SelectedItem is not SourceConfig source)return;try{using var json=await _api.GetDetailAsync(source.Url,video.Id);var item=json.RootElement.ValueKind==System.Text.Json.JsonValueKind.Object&&json.RootElement.TryGetProperty("list",out var list)&&list.ValueKind==System.Text.Json.JsonValueKind.Array&&list.GetArrayLength()>0?list[0]:json.RootElement;var detail=VideoDetailMapper.FromJson(item);if(detail.Episodes.Count>0){new EpisodeWindow(detail,_playback){Owner=this}.Show();}else MessageBox.Show($"{detail.Name}\n\n年份：{detail.Year ?? "未知"}\n导演：{detail.Director ?? "未知"}\n演员：{detail.Cast ?? "未知"}\n暂无可播放集数\n\n{detail.Description ?? "暂无简介"}","影片详情");}catch{MessageBox.Show($"{video.Name}\n\n年份：{video.Year ?? "未知"}\n备注：{video.Remark ?? "暂无"}","影片详情");}}
}
